### PR TITLE
Fixed handling of IN (subquery) expressions.

### LINKED ISSUE #391: `IN (SELECT ...)` bypasses `make_bucket_scan`
```
prop_test=> SELECT city FROM customers GROUP BY 1;
  city  
--------
 Rome
 Berlin
 Madrid
 London
 Paris
(5 rows)

prop_test=> SELECT 'Oslo' IN (SELECT city FROM customers GROUP BY 1);
 ?column? 
----------
 t
(1 row)
```

`Oslo` does appear in the non-anonymized result of the inner query, so we're effectively bypassing pg_diffix here. See also:

```
prop_test=> explain SELECT 'Oslo' IN (SELECT city FROM customers GROUP BY 1);
             QUERY PLAN              
-------------------------------------
 Result
   SubPlan 1
     ->  HashAggregate
           Group Key: customers.city
           ->  Seq Scan on customers
(5 rows)

prop_test=> explain SELECT * FROM (SELECT city FROM customers GROUP BY 1) x;
               QUERY PLAN                
-----------------------------------------
 Subquery Scan on x
   ->  Custom Scan (BucketScan)
         ->  HashAggregate
               Group Key: customers.city
               ->  Seq Scan on customers
(5 rows)
```

So what works for "regular" subqueries (latter), doesn't for x IN SELECT (former).

Cristian: "looks like we don't properly recurse into `IN (SELECT...)` expressions"

### PR DESCRIPTION
**Pull request by cristianberneanu**
Turns out after all, the problem was simpler than we initially thought. Closes #391.

### CODE REVIEW

File: pg_diffix/query/anonymization.h [hunk 1]
```diff
@@ -18,6 +18,11 @@ typedef struct AnonQueryLinks AnonQueryLinks;
...
 extern AnonQueryLinks *compile_query(Query *query, List *personal_relations);
 
+/*
+ * Calls `rewrite_plan` for each item in a list of Plan nodes.
+ */
+extern void rewrite_plan_list(List *plans, AnonQueryLinks *links);
+
 /*
  * Wraps anonymizing Agg nodes with BucketScan nodes. Does nothing if links is NULL.
  * Frees memory associated with links after rewriting.
```
Comment (edongashi) [inline pg_diffix/query/anonymization.h:28]: > Frees memory associated with links after rewriting.

Not sure if the comment is out of date or if it really does it. In that case we can't call it twice.

Comment (edongashi) [reply pg_diffix/query/anonymization.h:28]: I don't see it doing any such thing, meaning the function doc is wrong.

**Review by edongashi — DISMISSED** [review]

**Review by edongashi — APPROVED** [review]

**Comment by cristianberneanu** [comment]
Damn, merged into `master` instead of first merging into `release/elm`. Will make a new PR for Elm.
