### PR TITLE
Minor tweaks part 2

### LINKED ISSUE #320: pg_catalog is not visible to anon mode users
Everyone should be able to inspect the security labels of tables/columns via `SELECT * FROM diffix.show_labels()`.
Right now it fails for non-direct users, saying `permission denied for schema pg_catalog`.

### PR DESCRIPTION
**Pull request by pdobacz**
I've got some more unrelated tweaks

1/ I missed that the `jq` was a new addition, so I missed that the main image doesn't work anymore. This should fix it
2/ Something I hinted on earlier - our docs stated that there is a single *-bucket row, while there can be many
3/ A follow up after my recent `pg_catalog` work - this code littering `pg_validation` hurt my eyes, so I moved it to allowed_functions and renamed the file, I think this fits in nicely there.
4/ fix #320

### CODE REVIEW

File: pg_diffix/query/allowed_functions.h [hunk 1]
```diff
@@ -28,4 +30,10 @@ extern bool is_substring_builtin(Oid funcoid);
  */
 extern bool is_implicit_range_builtin_untrusted(Oid funcoid);
 
+/*
+ * Returns whether the OID points to a relation in the `pg_catalog`, for which accessing the
+ * `selected_cols` is allowed.
```
Comment (edongashi) [inline pg_diffix/query/allowed_functions.h:35]: Will the formatter revert back if changed like this?

```suggestion
 * Returns whether the OID points to a relation in the `pg_catalog`,
 * for which accessing the `selected_cols` is allowed.
```

**Review by edongashi — DISMISSED** [review]

File: pg_diffix/query/allowed_functions.h (hunk 1 above)
Comment (edongashi) [reply pg_diffix/query/allowed_functions.h:35]: I'm not sure I understand the function comment in either case.

It should just say whether the given catalog table and select columns are allowed.

Also the `rte` in the name is redundant.

Comment (pdobacz) [reply pg_diffix/query/allowed_functions.h:35]: Not the formatter but the rewrapper will make it a single line. For the sake of moving forward we can take your version.

Comment (pdobacz) [reply pg_diffix/query/allowed_functions.h]: re second comment, you're right, something went wrong there

Comment (pdobacz) [reply pg_diffix/query/allowed_functions.h]: ok, how about now?

**Review by edongashi — APPROVED** [review]
