### PR TITLE
Fix bug in argument insertion during rewriting of `count_histogram`.

### LINKED ISSUE #421: `count_histogram` tests on my system produce memory corruption warnings.
```
----------------------------------------------------------------
-- Anonymizing count_histogram
----------------------------------------------------------------
SET ROLE diffix_test;
SET pg_diffix.session_access_level = 'anonymized_trusted';
SELECT diffix.count_histogram(id) FROM count_histogram_test;
WARNING:  problem in alloc set ExecutorState: detected write past chunk end in block 0x7fffc7ddd8a0, chunk 0x7fffc7ddf700
WARNING:  problem in alloc set ExecutorState: detected write past chunk end in block 0x7fffc7ddd8a0, chunk 0x7fffc7ddf700
    count_histogram
------------------------
 {{NULL,3},{1,4},{2,3}}
(1 row)

SELECT diffix.count_histogram(id, 5) FROM count_histogram_test;
 count_histogram
-----------------
 {{0,7},{5,2}}
(1 row)

----------------------------------------------------------------
-- Misc
----------------------------------------------------------------
SELECT diffix.unnest_histogram(x.histogram)
FROM (
  SELECT diffix.count_histogram(id) AS histogram
  FROM count_histogram_test
) x;
WARNING:  problem in alloc set ExecutorState: detected write past chunk end in block 0x7fffc7e0b540, chunk 0x7fffc7e0bad8
WARNING:  problem in alloc set ExecutorState: detected write past chunk end in block 0x7fffc7e0b540, chunk 0x7fffc7e0bad8
 unnest_histogram
------------------
 {NULL,3}
 {1,4}
 {2,3}
(3 rows)
```

### PR DESCRIPTION
**Pull request by cristianberneanu**
Closes #421.

### CODE REVIEW

File: src/query/anonymization.c [hunk 1]
```diff
@@ -173,14 +173,15 @@ static void rewrite_count_histogram(Aggref *aggref, List *aid_refs)
...
-  list_nth_cell(aggref->args, 0)->ptr_value = makeTargetEntry(
+  list_head(aggref->args)->ptr_value = makeTargetEntry(
       make_const_int32(counted_aid_index), 1 /* resno */, "counted_aid_index", false);
 
   if (list_length(aggref->args) < 2)
   {
     /* Append implicit bin_size=1. */
     Assert(list_length(aggref->args) == 1);
     aggref->args = lappend(aggref->args, makeTargetEntry(make_const_int64(1), 2 /* resno */, "bin_size", false));
+    aggref->aggargtypes = lappend_oid(aggref->aggargtypes, INT8OID);
```
Comment (edongashi) [inline src/query/anonymization.c:184]: Do we also need to patch argtype at index 0?

**Review by edongashi — DISMISSED** [review]

File: src/query/anonymization.c (hunk 1 above)
Comment (cristianberneanu) [reply src/query/anonymization.c:184]: Yeah, good point, that would make sense as well.
